# Generated by Django 4.2.7 on 2025-08-06 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('source', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('scraped_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_date', '-scraped_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('source', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('keywords', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('scraped_date', models.DateTimeField(auto_now_add=True)),
                ('news_prompt', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
