# Generated by Django 4.2.7 on 2025-07-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Idea_generation', '0002_newsarticle_content_newsarticle_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
