# Generated by Django 5.2.4 on 2025-07-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Idea_generation', '0004_newsarticles'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='idea_prompt',
            field=models.TextField(blank=True),
        ),
    ]
