# Generated by Django 5.2.4 on 2025-07-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Idea_generation', '0005_newsarticle_idea_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='idea_prompt',
        ),
    ]
