# Generated by Django 5.2.4 on 2025-07-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Idea_generation', '0006_remove_newsarticle_idea_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticles',
            name='news_prompt',
            field=models.TextField(blank=True),
        ),
    ]
